apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - url: https://hooks.slack.com/services/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
          payload: >-
            {"text":"Hello, World!"}
          headers:
            - key: Content-type
              value: application/json
          method: POST
      subscriptionID: 619c8ac1-7969-4437-a4bf-a94d11e03f65
      sendFinished: false
      sendStarted: false
